INSERT INTO productos (nombre, presentacion, categoria, created_at, updated_at)
VALUES
    ('BOLA DE CERVEZA XICO', 1000, 'Otro', NOW(), NOW()),
    ('CHARLOTTE SALCHICHA DE POLLO JUMBO KG', 1000, 'Salchicha', NOW(), NOW()),
    ('CHORIZO AHUMADO ESPAÑOL', 1000, 'Chorizo', NOW(), NOW()),
    ('CHORIZO ARGENTINO', 1000, 'Chorizo', NOW(), NOW()),
    ('CHORIZO DE CERDO XICO', 1000, 'Chorizo', NOW(), NOW()),
    ('CHULETA AHUMADA REBANADA GRANEL', 1000, 'Carne', NOW(), NOW()),
    ('COSTILLA ADOBADA CARGADA', 1000, 'Carne', NOW(), NOW()),
    ('COSTILLA ADOBADA SENCILLA', 1000, 'Carne', NOW(), NOW()),
    ('COSTILLA AHUMADA ADOBADA', 1000, 'Carne', NOW(), NOW()),
    ('CUERITOS XICO DE CERDO EN VINAGRE', 1000, 'Cueros', NOW(), NOW()),
    ('DEL MANTEL JAMON VIRGINIA DE PAVO', 1000, 'Jamón', NOW(), NOW()),
    ('DEL MANTEL SALCHICHA PARA ASAR 800GR', 800, 'Salchicha', NOW(), NOW()),
    ('DEL MANTEL SALCHICHA POLACA', 1000, 'Salchicha', NOW(), NOW()),
    ('EMBUTIDO PARA TACOS DISCADA KG', 400, 'Otro', NOW(), NOW()),
    ('ENCURTIDOS XICO CUERITOS Y SALCHICHAS...', 1000, 'Salchicha', NOW(), NOW()),
    ('JAMON DE PAVO (CUADRADO)', 1000, 'Jamón', NOW(), NOW()),
    ('JAMÓN HORNEADO REBANADO', 1000, 'Jamón', NOW(), NOW()),
    ('JAMON TOBY AMERICANO CERDO Y PAVO KG', 1000, 'Jamón', NOW(), NOW()),
    ('JAMON TOBY PAVO KG', 1000, 'Jamón', NOW(), NOW()),
    ('JAMON TOBY PAVO VIRGINIA KG', 1000, 'Jamón', NOW(), NOW()),
    ('JAMÓN WINDSOR PECHUGA NATURAL KG', 1000, 'Jamón', NOW(), NOW()),
    ('JAMÓN XICO AMERICANO PAVO Y CERDO KG', 1000, 'Jamón', NOW(), NOW()),
    ('JAMÓN XICO EMBUTIDO TACOS PASTOR KG', 1000, 'Jamón', NOW(), NOW()),
    ('JAMON XICO PAVO AMERICANO KG', 1000, 'Jamón', NOW(), NOW()),
    ('JAMON XICO PAVO KG', 1000, 'Jamón', NOW(), NOW()),
    ('JAMÓN XICO SELVA NEGRA', 1000, 'Jamón', NOW(), NOW()),
    ('JAMÓN XICO VIRGINIA DE PAVO KG', 1000, 'Jamón', NOW(), NOW()),
    ('JAMON XICO VIRGINIA KG', 1000, 'Jamón', NOW(), NOW()),
    ('JAMON XICO YORK PIERNA DE CERDO KG', 1000, 'Jamón', NOW(), NOW()),
    ('LOMO XICO AHUMADO', 1000, 'Carne', NOW(), NOW()),
    ('LONGANIZA DE CERDO XICO', 1000, 'Chorizo', NOW(), NOW()),
    ('LONGANIZA WINDSOR CERDO 500G', 500, 'Chorizo', NOW(), NOW()),
    ('MORTADELA XICO', 1000, 'Mortadela', NOW(), NOW()),
    ('PASTEL XICO PIMIENTO KG', 1000, 'Otro', NOW(), NOW()),
    ('PEPERONI WINDSOR', 1000, 'Peperoni', NOW(), NOW()),
    ('PIERNA AL HORNO', 1000, 'Carne', NOW(), NOW()),
    ('PIERNA XICO CERDO AHUMADA', 1000, 'Carne', NOW(), NOW()),
    ('QUESO DE PUERCO XICO', 1000, 'Queso', NOW(), NOW()),
    ('SALCHICHA DE PAVO AL PASTOR', 1000, 'Salchicha', NOW(), NOW()),
    ('SALCHICHA DE PAVO JUMBO', 1000, 'Salchicha', NOW(), NOW()),
    ('SALCHICHA DE PAVO XICO', 1000, 'Salchicha', NOW(), NOW()),
    ('SALCHICHA HOT DOG XICO', 1000, 'Salchicha', NOW(), NOW()),
    ('SALCHICHA TOBY HOT DOG KG', 1000, 'Salchicha', NOW(), NOW()),
    ('SALCHICHA TOBY PARA ASAR KG', 1000, 'Salchicha', NOW(), NOW()),
    ('SALCHICHA TOBY PAVO KG', 1000, 'Salchicha', NOW(), NOW()),
    ('SALCHICHA XICO ASAR 800G', 800, 'Salchicha', NOW(), NOW()),
    ('SALCHICHA XICO PARA ASAR KG', 1000, 'Salchicha', NOW(), NOW()),
    ('SALCHICHA XICO PAVO HOT DOG KG', 1000, 'Salchicha', NOW(), NOW()),
    ('SALCHICHA XICO VIENA KG', 1000, 'Salchicha', NOW(), NOW()),
    ('SALCHICHAS XICO JUMBO PAVO KG', 1000, 'Salchicha', NOW(), NOW()),
    ('TOCINO AHUMADO 1KG', 1000, 'Tocino', NOW(), NOW()),
    ('XICO PAVO AHUMADO', 1000, 'Otro', NOW(), NOW()),
    ('XICO RECORTE DE JAMON', 1000, 'Jamón', NOW(), NOW()),
    ('XICO RECORTE DE SALCHICHA', 1000, 'Salchicha', NOW(), NOW()),
    ('XICO RECORTE DE SALCHICHA PARA ASAR', 1000, 'Salchicha', NOW(), NOW()),
    ('XICO SALAMI AHUMADO REBANADO', 1000, 'Salami', NOW(), NOW()),
    ('XICO VARIEDAD DE CARNES FRIAS', 1000, 'Carne', NOW(), NOW());
